### ISSUE TITLE
Scanning existing images via Share button not working

### ISSUE THREAD

**Issue by glowinthedark** [Fr4gorSoftware/SecScanQR#127]
Sharing an existing image via the Share button in any image viewing app is not working.

## Steps to reproduce

1. Open an image containing a QR code in any image viewer app.
1. Tap the Share button, and in the list of apps select SeqScanQR.

### Expected result
The QR code is decoded.

### Actual result
The regular SeqScanQR UI is displayed and the image is not processed.

Exception thrown (and swallowed) in `de.t_dankworth.secscanqr.activities.MainActivity.handleSendPicture():425`:
```stacktrace
com.google.zxing.NotFoundException
```
The `Toast` text from the catch block is **not** displayed because `.show()` is missing:

I.e. Instead of 
```java
Toast.makeText(activity, 
    getResources().getText(R.string.error_code_not_found), 
    Toast.LENGTH_LONG);
```

should be
```java
    Toast.makeText(activity, getResources().getText(R.string.error_code_not_found), 
    Toast.LENGTH_LONG).show();
```

> the toast is just a cosmetic thing; has nothing to do with the image not being decoded.

### NOTES
The same QR code is successfully decoded when the camera is used.

### Dirty workaround
@Fr4gorSoftware: Made a [pull request](/Fr4gorSoftware/SecScanQR/issues/128) which **does not** fix the way zxing is decoding the file from the image sharing intent. Instead it is relying on google `com.google.android.gms:play-services-vision` API to decode the image. This will crash on devices without GMS. This is not a proper solution, and something cleaner should be used. Or maybe the presence of GMS should be detected via reflection and used as a fallback when zxing cannot do the decoding.

**Comment by Fr4gorSoftware** [comment]
Thank you for the notice. I will fix that with the next version. 
I will take a look at the workaround too. Would be good if you could say in which scenarios GMS could help decode the QR Code.

**Comment by glowinthedark** [comment]
@Fr4gorSoftware: The scenarios when GMS works but secscanqr doesn't (after fixing the image type from `image/*` to something more permissive) is image size too large ie 2000x4000 as well as some images shared for example from a webpage. 

I had a look (with jadx ) at Xiaomi's Mi Scanner which is a system app preinstalled in MIUI and which is also using zxing yet it seems to have a higher success rate in various use cases and also handles WiFi, vcal events and a bunch of other specialized qr codes. Ie my assumption is that it's just some configurations that might be missing.

**Comment by Fr4gorSoftware** [comment]
I think a found the problem. With this [version](https://github.com/Fr4gorSoftware/SecScanQR/tree/fix-shared-qrcode) the points you mentioned were fixed on my side. Can you check if it is the same on your side?

**Comment by glowinthedark** [comment]
@Fr4gorSoftware: Installed branch **fix-shared-qrcode** and scanning via Share intent is still not working.

This is the version I tested on
```
commit 44c64af928ff3d819fd551f0a28be904a591ae22 (HEAD -> fix-shared-qrcode, origin/fix-shared-qrcode)
Author: Thore <30445568+Fr4gorSoftware@users.noreply.github.com>
Date:   Sun Jan 12 22:16:09 2020 +0100

    fix shared qrcode
```

The toast now appears (as opposed to before): `File not found`.

Tested on several different images containing qr codes and failed on all. The image is a regular jpg image that can be successfully scanned by other scanners, including by by secscanqr when using the camera, but sharing from the gallery app via intent is not working.

sample image:
https://user-images.githubusercontent.com/48893368/73138500-883f2100-4063-11ea-8917-685290efef3f.jpg

**Comment by Fr4gorSoftware** [comment]
I tested it with several pictures but with the jpg you mentioned it also did not worked on my side. I think ZXing can't recognize it but in general the problem you mentioned is fixed and works now for more pictures then before but there is no warranty that it will work with a specific picture.

For a release in the future I will try to implement a crop tool for images. Maybe this will help too.
